on:
  workflow_dispatch:

name: Airflow Dags Deploy
run-name: "Deploy DAGs"

permissions:
  id-token: write # This is required for AWS OIDC
  contents: read

env:
  AWS_REGION: ${{ vars['AWS_REGION'] }}

jobs:
  deploy:
    name: "Deploy DAGs"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars['DEPLOYMENT_ROLE_TO_ASSUME'] }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync files to S3
        id: s3_files_sync
        shell: bash
        run: |
          set -o errexit
          aws s3 sync dags s3://labs-airflow-bucket/dags --delete --no-follow-symlinks --dryrun
